In [2]:
from transformers import AutoModel, AutoModelForImageClassification
import torch
import torchvision

In [3]:
model = AutoModel.from_pretrained("microsoft/swinv2-base-patch4-window16-256")
classifier_model = AutoModelForImageClassification.from_pretrained("microsoft/swinv2-base-patch4-window16-256")

C:\Users\Amar\Git\chest-x-ray-classifier\venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


In [47]:
dummy_input = torch.randn(4, 3, 64, 64)

In [8]:
output = model(dummy_input)

In [12]:
output

Swinv2ModelOutput(last_hidden_state=tensor([[[-0.0803, -0.0234, -0.1582,  ..., -0.0986, -0.0011, -0.0960],
         [-0.0656, -0.1820, -0.1115,  ..., -0.1515, -0.1538, -0.2688],
         [-0.0998,  0.0283, -0.0950,  ..., -0.1509, -0.1371, -0.1468],
         [ 0.0907,  0.0003, -0.1615,  ..., -0.2218, -0.0874, -0.1254]],

        [[-0.0556, -0.0632, -0.1737,  ..., -0.0891, -0.0492, -0.1333],
         [-0.1872,  0.0496, -0.0690,  ..., -0.0999, -0.1099,  0.0319],
         [-0.1471, -0.0031, -0.0725,  ..., -0.1007, -0.0143, -0.1815],
         [-0.1286,  0.0717, -0.0755,  ..., -0.1538, -0.1152, -0.1157]],

        [[-0.0784, -0.0250, -0.0873,  ..., -0.0989, -0.1463, -0.2100],
         [-0.0441, -0.0614, -0.1123,  ..., -0.1135, -0.0937, -0.1441],
         [-0.1517, -0.0231, -0.0558,  ..., -0.1646, -0.0602, -0.2877],
         [-0.0904, -0.0202, -0.0871,  ..., -0.1745, -0.0975, -0.1295]],

        [[-0.0824, -0.0309, -0.1365,  ..., -0.1018,  0.0193, -0.0958],
         [-0.1056,  0.0027, -0.0686

In [13]:
logits = classifier_model(dummy_input)
logits

Swinv2ImageClassifierOutput(loss=None, logits=tensor([[-0.3284, -0.0325,  0.0598,  ..., -0.0114, -0.0010,  0.1994],
        [-0.1365,  0.0166,  0.0262,  ...,  0.0643,  0.1996,  0.2237],
        [-0.2058, -0.0294,  0.1991,  ...,  0.0333,  0.1115,  0.3279],
        [-0.1488,  0.1560,  0.3246,  ...,  0.1174,  0.2852,  0.1444]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None, reshaped_hidden_states=None)

In [14]:
logits.logits

tensor([[-0.3284, -0.0325,  0.0598,  ..., -0.0114, -0.0010,  0.1994],
        [-0.1365,  0.0166,  0.0262,  ...,  0.0643,  0.1996,  0.2237],
        [-0.2058, -0.0294,  0.1991,  ...,  0.0333,  0.1115,  0.3279],
        [-0.1488,  0.1560,  0.3246,  ...,  0.1174,  0.2852,  0.1444]],
       grad_fn=<AddmmBackward0>)

In [16]:
from transformers import Dinov2ForImageClassification, ConvNextV2ForImageClassification, ConvNextForImageClassification, SwinForImageClassification, Swinv2ForImageClassification

In [17]:
dino = Dinov2ForImageClassification.from_pretrained("microsoft/dino-patch16-224")

OSError: microsoft/dino-vits16-patch16-224 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

In [18]:
from torchvision.models import swin_v2_b 

In [19]:
swin = swin_v2_b()

In [20]:
from transformers import SwinForImageClassification

In [48]:
output = model(dummy_input)
output

tensor([[-0.8437,  0.0754,  1.3861,  ...,  0.1153, -0.0851,  0.5369],
        [ 1.1750, -0.1091, -0.7431,  ..., -0.3298,  0.1594,  0.7720],
        [-0.6534, -0.8041,  0.4562,  ...,  0.0322,  1.0977,  0.9998],
        [-0.7494, -0.0963, -0.0968,  ..., -0.5811,  0.2786, -0.7411]],
       grad_fn=<AddmmBackward0>)

In [22]:
pooled_output = output[0]
pooled_output

tensor([[[-0.0803, -0.0234, -0.1582,  ..., -0.0986, -0.0011, -0.0960],
         [-0.0656, -0.1820, -0.1115,  ..., -0.1515, -0.1538, -0.2688],
         [-0.0998,  0.0283, -0.0950,  ..., -0.1509, -0.1371, -0.1468],
         [ 0.0907,  0.0003, -0.1615,  ..., -0.2218, -0.0874, -0.1254]],

        [[-0.0556, -0.0632, -0.1737,  ..., -0.0891, -0.0492, -0.1333],
         [-0.1872,  0.0496, -0.0690,  ..., -0.0999, -0.1099,  0.0319],
         [-0.1471, -0.0031, -0.0725,  ..., -0.1007, -0.0143, -0.1815],
         [-0.1286,  0.0717, -0.0755,  ..., -0.1538, -0.1152, -0.1157]],

        [[-0.0784, -0.0250, -0.0873,  ..., -0.0989, -0.1463, -0.2100],
         [-0.0441, -0.0614, -0.1123,  ..., -0.1135, -0.0937, -0.1441],
         [-0.1517, -0.0231, -0.0558,  ..., -0.1646, -0.0602, -0.2877],
         [-0.0904, -0.0202, -0.0871,  ..., -0.1745, -0.0975, -0.1295]],

        [[-0.0824, -0.0309, -0.1365,  ..., -0.1018,  0.0193, -0.0958],
         [-0.1056,  0.0027, -0.0686,  ..., -0.1054,  0.0802, -0.3083],


In [25]:
from torchvision.models import swin_v2_b
from torch.nn import Sequential

In [40]:
model = swin_v2_b()
model

SwinTransformer(
  (features): Sequential(
    (0): Sequential(
      (0): Conv2d(3, 128, kernel_size=(4, 4), stride=(4, 4))
      (1): Permute()
      (2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    )
    (1): Sequential(
      (0): SwinTransformerBlockV2(
        (norm1): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
        (attn): ShiftedWindowAttentionV2(
          (qkv): Linear(in_features=128, out_features=384, bias=True)
          (proj): Linear(in_features=128, out_features=128, bias=True)
          (cpb_mlp): Sequential(
            (0): Linear(in_features=2, out_features=512, bias=True)
            (1): ReLU(inplace=True)
            (2): Linear(in_features=512, out_features=4, bias=False)
          )
        )
        (stochastic_depth): StochasticDepth(p=0.0, mode=row)
        (norm2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
        (mlp): MLP(
          (0): Linear(in_features=128, out_features=512, bias=True)
          (1): GELU(appro

In [49]:
partial_a = Sequential(*list(model.children())[:-3])
partial_b = Sequential(*list(model.children())[:-4])
partial_c = model.features

print(partial_a(dummy_input).shape)
print(partial_b(dummy_input).shape)
print(partial_c(dummy_input).shape)

torch.Size([4, 1024, 2, 2])
torch.Size([4, 2, 2, 1024])
torch.Size([4, 2, 2, 1024])


In [30]:
from transformers import Swinv2Model

In [31]:
hg_swin = Swinv2Model.from_pretrained("microsoft/swinv2-base-patch4-window16-256")

In [32]:
print(hg_swin)

Swinv2Model(
  (embeddings): Swinv2Embeddings(
    (patch_embeddings): Swinv2PatchEmbeddings(
      (projection): Conv2d(3, 128, kernel_size=(4, 4), stride=(4, 4))
    )
    (norm): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.0, inplace=False)
  )
  (encoder): Swinv2Encoder(
    (layers): ModuleList(
      (0): Swinv2Stage(
        (blocks): ModuleList(
          (0-1): 2 x Swinv2Layer(
            (attention): Swinv2Attention(
              (self): Swinv2SelfAttention(
                (continuous_position_bias_mlp): Sequential(
                  (0): Linear(in_features=2, out_features=512, bias=True)
                  (1): ReLU(inplace=True)
                  (2): Linear(in_features=512, out_features=4, bias=False)
                )
                (query): Linear(in_features=128, out_features=128, bias=True)
                (key): Linear(in_features=128, out_features=128, bias=False)
                (value): Linear(in_features=128, out_features=12

In [50]:
output = hg_swin(dummy_input)
output

Swinv2ModelOutput(last_hidden_state=tensor([[[-1.2145e-01, -1.4345e-01, -1.9764e-01,  ..., -7.1411e-02,
          -7.4332e-02, -4.5897e-01],
         [-1.5069e-01,  1.8928e-03, -3.5361e-02,  ..., -1.5503e-01,
          -3.3835e-02, -6.1100e-02],
         [-1.1029e-01, -1.5225e-02, -6.6422e-02,  ..., -1.0347e-01,
          -2.2200e-02, -2.4258e-04],
         [-9.1041e-02,  4.2028e-02, -4.7165e-02,  ..., -1.2793e-01,
           1.3967e-02, -5.3806e-02]],

        [[-1.4003e-01, -9.2948e-02, -1.3430e-01,  ..., -9.0222e-02,
          -1.6096e-01, -2.4195e-01],
         [-2.2246e-01, -5.3050e-02, -1.3448e-01,  ..., -1.4318e-01,
          -1.0729e-01, -1.8262e-01],
         [-1.1345e-01,  1.0924e-02, -8.0022e-02,  ..., -6.9763e-02,
          -7.1561e-02,  1.1568e-02],
         [ 1.1089e-02,  4.0826e-02, -2.6907e-02,  ..., -2.1621e-01,
          -1.0172e-02, -9.2461e-02]],

        [[-1.6711e-01, -6.8040e-02, -1.4898e-01,  ..., -9.6711e-02,
          -1.6453e-01, -3.0842e-01],
         [-1.86

In [51]:
output[1].shape

torch.Size([4, 4096])

In [37]:
hg_swin.pooler = torch.nn.Identity()

In [38]:
output = hg_swin(dummy_input)
output

Swinv2ModelOutput(last_hidden_state=tensor([[[-0.0803, -0.0234, -0.1582,  ..., -0.0986, -0.0011, -0.0960],
         [-0.0656, -0.1820, -0.1115,  ..., -0.1515, -0.1538, -0.2688],
         [-0.0998,  0.0283, -0.0950,  ..., -0.1509, -0.1371, -0.1468],
         [ 0.0907,  0.0003, -0.1615,  ..., -0.2218, -0.0874, -0.1254]],

        [[-0.0556, -0.0632, -0.1737,  ..., -0.0891, -0.0492, -0.1333],
         [-0.1872,  0.0496, -0.0690,  ..., -0.0999, -0.1099,  0.0319],
         [-0.1471, -0.0031, -0.0725,  ..., -0.1007, -0.0143, -0.1815],
         [-0.1286,  0.0717, -0.0755,  ..., -0.1538, -0.1152, -0.1157]],

        [[-0.0784, -0.0250, -0.0873,  ..., -0.0989, -0.1463, -0.2100],
         [-0.0441, -0.0614, -0.1123,  ..., -0.1135, -0.0937, -0.1441],
         [-0.1517, -0.0231, -0.0558,  ..., -0.1646, -0.0602, -0.2877],
         [-0.0904, -0.0202, -0.0871,  ..., -0.1745, -0.0975, -0.1295]],

        [[-0.0824, -0.0309, -0.1365,  ..., -0.1018,  0.0193, -0.0958],
         [-0.1056,  0.0027, -0.0686

In [39]:
output[1].shape

torch.Size([4, 4096])