In [1]:
from PIL import Image
import numpy as np
import os
import tqdm
import pandas as pd

In [3]:
# root = "/home/amar/Datasets/X-ray/CheXpert/CheXpert/"
root = "E:/Datasets/CheXpert-v1.0-small/CheXpert-v1.0-small/"

In [6]:
train_csv = "F:/CheXpert-v1.0/train.csv"
valid_csv = "F:/CheXpert-v1.0/valid.csv"

In [7]:
train_labels = pd.read_csv(train_csv)
val_labels = pd.read_csv(valid_csv)

In [8]:
len(train_labels), len(val_labels)

(223414, 234)

In [12]:
train_images = []
train_images_renamed = []
patients = os.listdir(train_dir)
for i, patient in tqdm.tqdm(enumerate(patients), total=len(patients)):
    studies = os.listdir(train_dir + patient)
    for j, study in enumerate(studies):
        images = os.listdir(train_dir+patient+'/'+study)
        for k, img in enumerate(images):
            train_images.append(train_dir+patient+'/'+study+'/'+img)
            train_images_renamed.append(root+'train_renamed/'+patient+'_'+study+'_'+img)

100%|███████████████████████████████████████████████████████████████████████████| 64540/64540 [05:17<00:00, 203.37it/s]


In [13]:
val_images = []
val_images_renamed = []
patients = os.listdir(val_dir)
for i, patient in tqdm.tqdm(enumerate(patients), total=len(patients)):
    studies = os.listdir(val_dir + patient)
    for j, study in enumerate(studies):
        images = os.listdir(val_dir+patient+'/'+study)
        for k, img in enumerate(images):
            val_images.append(val_dir+patient+'/'+study+'/'+img)
            val_images_renamed.append(root+'val_renamed/'+patient+'_'+study+'_'+img)

100%|███████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 381.66it/s]


In [14]:
len(train_images_renamed), len(val_images_renamed)

(223415, 234)

In [8]:
import shutil

In [9]:
for i in tqdm.tqdm(range(len(train_images))):
  shutil.move(train_images[i], train_images_renamed[i])

100%|██████████| 32387/32387 [00:00<00:00, 33419.29it/s]


In [10]:
for i in tqdm.tqdm(range(len(val_images))):
  shutil.move(val_images[i], val_images_renamed[i])

100%|██████████| 32/32 [00:00<00:00, 17501.33it/s]


In [11]:
import pandas as pd

Training

In [74]:
data = pd.read_csv(root+"label_information/train.csv")
data = data.drop(labels=['Sex', 'Age', 'AP/PA'], axis=1)
data['Path'] = data['Path'].map(lambda x: x.replace('CheXpert-v1.0-small/train/', ''))
data['Path'] = data['Path'].map(lambda x: x.replace('/', '_'))
#data['Path'] = data['Path'].map(lambda x: 'C:/Users/Amar/Datasets/CheXpert/CheXpert/train_renamed/' + x)
data = data.loc[data['Frontal/Lateral'] == 'Frontal']
data = data.drop(labels='Frontal/Lateral', axis=1)

In [75]:
labels = data[data.keys()[2:]]
labels = labels.values
index = data.index.values.tolist()
uncertain = []
for i in range(len(labels)):
    if -1 in labels[i]:
        uncertain.append(index[i])

In [34]:
data = data.drop(index=uncertain)

In [35]:
files = data['Path'].tolist()
label_nf = data['No Finding'].tolist()
#for i, entry in enumerate(files):
#    files[i] = entry.replace(prefix, '')

In [38]:
import math

In [39]:
for i, label in enumerate(label_nf):
    if math.isnan(label):
        label_nf[i] = 0
    else:
        label_nf[i] = 1

In [41]:
import csv

In [42]:
train_rows = zip(files, label_nf)
with open('/home/amar/Datasets/X-ray/CheXpert/CheXpert/normal_frontal_split/train.csv', 'w') as f:
    writer = csv.writer(f)
    for row in train_rows:
        writer.writerow(row)

Validation

In [77]:
data = pd.read_csv(root+"label_information/valid.csv")
data = data.drop(labels=['Sex', 'Age', 'AP/PA'], axis=1)
data['Path'] = data['Path'].map(lambda x: x.replace('CheXpert-v1.0-small/valid/', ''))
data['Path'] = data['Path'].map(lambda x: x.replace('/', '_'))
data = data.loc[data['Frontal/Lateral'] == 'Frontal']
data = data.drop(labels='Frontal/Lateral', axis=1)

In [84]:
labels = data[data.keys()[2:]]
labels = labels.values
index = data.index.values.tolist()
uncertain = []
for i in range(len(labels)):
    if -1 in labels[i]:
        uncertain.append(index[i])

In [89]:
files = data['Path'].tolist()
label_nf = data['No Finding'].tolist()

In [94]:
for i, label in enumerate(label_nf):
    label_nf[i] = int(label)

In [96]:
val_rows = zip(files, label_nf)
with open('/home/amar/Datasets/X-ray/CheXpert/CheXpert/normal_frontal_split/val.csv', 'w') as f:
    writer = csv.writer(f)
    for row in val_rows:
        writer.writerow(row)

In [97]:
np.sum(label_nf)/len(label_nf)

0.12871287128712872

In [99]:
path = '/home/amar/Datasets/X-ray/CheXpert/images/'

In [100]:
images = os.listdir(path)

In [104]:
from PIL import Image
import numpy as np

In [124]:
img = Image.open(path+images[6])
img = np.asarray(img)
img2 = Image.open(path+images[1])
img2 = np.asarray(img2)

In [134]:
import tqdm

In [136]:
x = []
y = []
max_x = 0
max_y = 0
for file in tqdm.tqdm(images, total=len(images)):
    img = np.asarray(Image.open(path+file))
    shape = img.shape
    if shape[0] > max_x:
        max_x = shape[0]
    if shape[1] > max_y:
        max_y = shape[1]
    x.append(shape[0])
    y.append(shape[1])
np.mean(x), np.mean(y)

100%|██████████| 223648/223648 [06:57<00:00, 535.75it/s]


(325.4738696523108, 372.7543282300758)

In [137]:
ratios = []
for file in tqdm.tqdm(images, total=len(images)):
    img = np.asarray(Image.open(path+file))
    shape = img.shape
    ratio = shape[0]/shape[1]
    ratios.append(ratio)
np.mean(ratios)

100%|██████████| 223648/223648 [05:33<00:00, 669.87it/s]


0.8814376147143383

In [138]:
max_x, max_y

(642, 930)

# Conventional Data Split

Using only frontal X-rays and excluding uncertain labels

In [21]:
import pandas as pd
import numpy as np
import tqdm

In [4]:
path = '/home/amar/Datasets/X-ray/CheXpert/normal_frontal_split/'

In [12]:
train_data = pd.read_csv(path+'train.csv', header=None)
val_data = pd.read_csv(path+'val.csv', header=None)

In [18]:
images = train_data[0].tolist() + val_data[0].tolist()
labels = train_data[1].tolist() + val_data[1].tolist()

In [20]:
len(images), len(labels)

(118488, 118488)

In [22]:
images

['patient00001_study1_view1_frontal.jpg',
 'patient00003_study1_view1_frontal.jpg',
 'patient00004_study1_view1_frontal.jpg',
 'patient00005_study1_view1_frontal.jpg',
 'patient00005_study2_view1_frontal.jpg',
 'patient00005_study2_view2_frontal.jpg',
 'patient00006_study1_view1_frontal.jpg',
 'patient00007_study1_view1_frontal.jpg',
 'patient00007_study2_view1_frontal.jpg',
 'patient00008_study1_view1_frontal.jpg',
 'patient00008_study2_view1_frontal.jpg',
 'patient00009_study1_view1_frontal.jpg',
 'patient00010_study1_view1_frontal.jpg',
 'patient00011_study13_view1_frontal.jpg',
 'patient00011_study5_view1_frontal.jpg',
 'patient00011_study7_view1_frontal.jpg',
 'patient00011_study2_view1_frontal.jpg',
 'patient00011_study10_view1_frontal.jpg',
 'patient00011_study11_view1_frontal.jpg',
 'patient00011_study8_view1_frontal.jpg',
 'patient00011_study12_view1_frontal.jpg',
 'patient00011_study3_view1_frontal.jpg',
 'patient00011_study6_view1_frontal.jpg',
 'patient00012_study3_view1_fr

In [27]:
images[0][0:12]

'patient00001'

In [28]:
patients = []
for image in tqdm.tqdm(images, total=len(images)):
    patient = image[0:12]
    if patient not in patients:
        patients.append(patient)

100%|██████████| 118488/118488 [00:38<00:00, 3072.80it/s]


In [30]:
len(patients)

49604

In [34]:
random_patients = np.random.choice(patients, size=len(patients), replace=False)

In [37]:
random_patients

array(['patient26912', 'patient36842', 'patient03884', ...,
       'patient12354', 'patient24548', 'patient09150'], dtype='<U12')

Only Train + Val Split, 90/10

In [38]:
train_patients = random_patients[0:44644]
val_patients = random_patients[44644:]

In [44]:
train_images = []
train_labels = []
val_images = []
val_labels = []
for i, image in tqdm.tqdm(enumerate(images), total=len(images)):
    patient = image[0:12]
    if patient in train_patients:
        train_images.append(image)
        train_labels.append(labels[i])
    else:
        val_images.append(image)
        val_labels.append(labels[i])

100%|██████████| 118488/118488 [01:20<00:00, 1464.32it/s]


In [41]:
train_patients

array(['patient26912', 'patient36842', 'patient03884', ...,
       'patient01785', 'patient26114', 'patient34408'], dtype='<U12')

In [45]:
len(train_images)

107210

In [46]:
len(val_images)

11278

In [52]:
import csv

In [53]:
train_rows = zip(train_images, train_labels)
with open(path + 'train1.csv', 'w') as f:
    writer = csv.writer(f)
    for row in train_rows:
        writer.writerow(row)

In [54]:
val_rows = zip(val_images, val_labels)
with open(path + 'val1.csv', 'w') as f:
    writer = csv.writer(f)
    for row in val_rows:
        writer.writerow(row)

Train/Val/Test split 70/10/20

In [55]:
random_patients = np.random.choice(patients, size=len(patients), replace=False)

In [57]:
train_patients = random_patients[0:34723]
val_patients = random_patients[34723:39683]
test_patients = random_patients[39683:]

In [61]:
train_images = []
train_labels = []
val_images = []
val_labels = []
test_images = []
test_labels = []
for i, image in tqdm.tqdm(enumerate(images), total=len(images)):
    patient = image[0:12]
    if patient in train_patients:
        train_images.append(image)
        train_labels.append(labels[i])
    elif patient in val_patients:
        val_images.append(image)
        val_labels.append(labels[i])
    else:
        test_images.append(image)
        test_labels.append(labels[i])

100%|██████████| 118488/118488 [01:03<00:00, 1853.67it/s]


In [62]:
train_rows = zip(train_images, train_labels)
with open(path + 'train2.csv', 'w') as f:
    writer = csv.writer(f)
    for row in train_rows:
        writer.writerow(row)

In [63]:
val_rows = zip(val_images, val_labels)
with open(path + 'val2.csv', 'w') as f:
    writer = csv.writer(f)
    for row in val_rows:
        writer.writerow(row)

In [64]:
test_rows = zip(test_images, test_labels)
with open(path + 'test2.csv', 'w') as f:
    writer = csv.writer(f)
    for row in test_rows:
        writer.writerow(row)

In [19]:
import pandas as pd
import numpy as np

In [4]:
path = '/home/amar/Datasets/X-ray/CheXpert/normal_frontal_split/'

In [9]:
train_df = pd.read_csv(path+'train2.csv', header=None)
val_df = pd.read_csv(path+'val2.csv', header=None)
test_df = pd.read_csv(path+'test2.csv', header=None)

In [24]:
np.sum(train_df[1])# /len(train_df[1])

11807

In [25]:
np.sum(val_df[1])#/len(val_df[1])

1704

In [26]:
np.sum(test_df[1])#/len(test_df[1])

3410

In [46]:
test = np.random.random([1, 5, 5, 3])

In [47]:
for img in test:
    print(img)

[[[0.02520262 0.29390169 0.81968459]
  [0.51909681 0.43250392 0.3349448 ]
  [0.42816512 0.48369192 0.56980977]
  [0.71519377 0.55678702 0.42045773]
  [0.93813737 0.18537666 0.24764392]]

 [[0.1502658  0.78428337 0.10500829]
  [0.80728318 0.57274079 0.8513385 ]
  [0.62794115 0.16871489 0.97738329]
  [0.09275306 0.49756543 0.00278183]
  [0.2988506  0.51112405 0.35144064]]

 [[0.30482643 0.17384223 0.57606041]
  [0.20991327 0.12439841 0.50005314]
  [0.59821798 0.27592079 0.14965001]
  [0.25295774 0.767504   0.93441025]
  [0.93479757 0.91397581 0.88195067]]

 [[0.64383585 0.50955755 0.28778009]
  [0.82592501 0.47835724 0.33372666]
  [0.76960273 0.49369655 0.99619262]
  [0.061791   0.83285596 0.17430329]
  [0.68006834 0.31954307 0.07142802]]

 [[0.1338428  0.36315923 0.73051793]
  [0.9000137  0.79145735 0.722534  ]
  [0.72806526 0.33595526 0.52324227]
  [0.19579478 0.21119886 0.47808478]
  [0.62543035 0.68155705 0.298746  ]]]
